main:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Team"
    url:  "/team"
  - name: "Blog"
    url:  "/blog"
social:
  - name: "Facebook"
    url:  "#"
  - name: "Twitter"
    url:  "#"
  - name: "Mastodon"
    url:  "#"
