main:
  - name: "Home"
    url: "/"
    weight: 10
  - name: "About"
    url: "/about"
    weight: 40
  - name: "Team"
    url:  "/team"
    weight: 30
  - name: "Blog"
    url:  "/blog"
    weight: 20
social:
  # - name: "Facebook"
  #   url:  "#facebook"
  - name: "Twitter"
    url:  "https://twitter.com/OSUMontreal"
  - name: "Mastodon"
    url:  "https://fosstodon.org/web/accounts/286300"
footer:
  - name: "Colophon"
    url:  "#"
    weight: 10
  - name: "Privacy"
    url:  "#"
    weight: 20
  - name: "Accessibility"
    url:  "#"
    weight: 30
