main:
  - name: "Home"
    url: "/"
    weight: 10
  - name: "About"
    url: "/about"
    weight: 40
  - name: "Team"
    url:  "/team"
    weight: 30
  - name: "Blog"
    url:  "/blog"
    weight: 20
social:
  - name: "Facebook"
    url:  "#"
  - name: "Twitter"
    url:  "#"
  - name: "Mastodon"
    url:  "#"
