main:
  - name: "Accueil"
    url:  "/"
    weight: 10
  - name: "À Propos"
    url: "/a-propos"
    weight: 40
  # - name: "Équipe"
  #   url:  "/equipe"
  #   weight: 30
  - name: "Blogue"
    url:  "/blogue"
    weight: 20
social:
  # - name: "Facebook"
  #   url:  "#facebook"
  - name: "Twitter"
    url:  "https://twitter.com/OSUMontreal"
  - name: "Mastodon"
    url:  "https://fosstodon.org/web/accounts/286300"
footer:
  - name: "Colophon"
    url:  "#"
    weight: 10
  - name: "Confidentialité"
    url:  "#"
    weight: 20
  - name: "Accessibilité"
    url:  "#"
    weight: 30
