main:
  - name: "Accueil"
    url:  "/"
  - name: "À Propos"
    url: "/a-propos"
  - name: "Équipe"
    url:  "/equipe"
  - name: "Blogue"
    url:  "/blogue"
social:
  - name: "Facebook"
    url:  "#"
  - name: "Twitter"
    url:  "#"
  - name: "Mastodon"
    url:  "#"
